In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
from scipy.stats import zscore
from scipy.stats import boxcox

from sklearn.linear_model import LinearRegression,LogisticRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.metrics import precision_score,recall_score,accuracy_score,f1_score,classification_report,confusion_matrix,multilabel_confusion_matrix
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

from sklearn.preprocessing import StandardScaler,MinMaxScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor


from sklearn.datasets import load_boston
import warnings
warnings.filterwarnings('ignore')
import pickle

In [60]:
df=pd.read_csv('diabetes.csv')
df

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,148,50,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,52,1
3,150,66,23,94,28.1,0.167,21,0
4,150,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,101,76,48,180,32.9,0.171,63,0
764,122,70,27,0,36.8,0.340,27,0
765,121,72,23,112,26.2,0.245,30,0
766,126,60,0,0,30.1,0.349,47,1
767,93,70,31,0,30.4,0.315,23,0

In [61]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [62]:
df.describe()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,121.117188,69.076823,20.536458,79.799479,31.992578,0.471876,33.243490,0.348958
std,31.805091,19.367794,15.952218,115.244002,7.884160,0.331329,11.758182,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,142.000000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## feature scaling

In [63]:
x_df=df.drop('Outcome',axis=1)
x_df.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,148,50,35,0,33.6,0.627,50
1,85,66,29,0,26.6,0.351,31
2,183,64,0,0,23.3,0.672,52
3,150,66,23,94,28.1,0.167,21
4,150,40,35,168,43.1,2.288,33

In [64]:
normal_scaler=MinMaxScaler()
arr=normal_scaler.fit_transform(x_df)
x_norm_df=pd.DataFrame(arr,columns=x_df.columns)
x_norm_df.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.743719,0.409836,0.353535,0.000000,0.500745,0.234415,0.483333
1,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667
2,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.516667
3,0.753769,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000
4,0.753769,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000

In [65]:
std_scaler=StandardScaler()
arr=std_scaler.fit_transform(x_df)
x_std_df=pd.DataFrame(arr,columns=x_df.columns)
x_std_df

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.845787,-0.985618,0.907270,-0.692891,0.204013,0.468492,1.426022
1,-1.136319,-0.158966,0.530902,-0.692891,-0.684422,-0.365061,-0.190927
2,1.946957,-0.262298,-1.288212,-0.692891,-1.103255,0.604397,1.596227
3,0.908711,-0.158966,0.154533,0.123302,-0.494043,-0.920763,-1.041953
4,0.908711,-1.502276,0.907270,0.765836,1.409746,5.484909,-0.020722
...,...,...,...,...,...,...,...
763,-0.632927,0.357691,1.722735,0.870031,0.115169,-0.908682,2.532356
764,0.027775,0.047697,0.405445,-0.692891,0.610154,-0.398282,-0.531337
765,-0.003687,0.151028,0.154533,0.279594,-0.735190,-0.685193,-0.276029
766,0.153623,-0.468961,-1.288212,-0.692891,-0.240205,-0.371101,1.170715
767,-0.884623,0.047697,0.656358,-0.692891,-0.202129,-0.473785,-0.871747

## train_test_split

In [66]:
x=df.drop('Outcome',axis=1)
y=df['Outcome']

In [67]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

In [51]:
# Normalization
x=x_norm_df.copy()
y=df['Outcome']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

In [52]:
# Standardization
x = x_std_df.copy()
y = df['Outcome']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 11)

## Model Training

In [68]:
knn_clf=KNeighborsClassifier()
knn_clf.fit(x_train,y_train)

KNeighborsClassifier()

## evaluation

In [69]:
# testing data evaluation

y_pred=knn_clf.predict(x_test)

cnf_matrix=confusion_matrix(y_test,y_pred)
print('Confusion Matrix is: \n', cnf_matrix)
print()
acc=accuracy_score(y_test,y_pred)
print('Accuracy is: ', acc)
print()
clf_report=classification_report(y_test,y_pred)
print('Classification Report is: \n',clf_report)

Confusion Matrix is:
 [[86 14]
 [29 25]]

Accuracy is:  0.7207792207792207

Classification Report is:
               precision    recall  f1-score   support

           0       0.75      0.86      0.80       100
           1       0.64      0.46      0.54        54

    accuracy                           0.72       154
   macro avg       0.69      0.66      0.67       154
weighted avg       0.71      0.72      0.71       154

In [70]:
# testing data evaluation

y_pred_train=knn_clf.predict(x_train)

cnf_matrix=confusion_matrix(y_train,y_pred_train)
print('Confusion Matrix is: \n', cnf_matrix)
print()
acc=accuracy_score(y_train,y_pred_train)
print('Accuracy is: ', acc)
print()
clf_report=classification_report(y_train,y_pred_train)
print('Classification Report is: \n',clf_report)

Confusion Matrix is:
 [[351  49]
 [ 66 148]]

Accuracy is:  0.8127035830618893

Classification Report is:
               precision    recall  f1-score   support

           0       0.84      0.88      0.86       400
           1       0.75      0.69      0.72       214

    accuracy                           0.81       614
   macro avg       0.80      0.78      0.79       614
weighted avg       0.81      0.81      0.81       614

## Hyper Parameter Tuning

In [71]:
knn_clf=KNeighborsClassifier()
hyp={'n_neighbors':np.arange(4,35),'p':[1,2]} # 1=manhatten distance,2=uclidean distance
gscv_knn=GridSearchCV(knn_clf,hyp,cv=5)
gscv_knn.fit(x_train,y_train)
gscv_knn.best_estimator_

KNeighborsClassifier(n_neighbors=33, p=1)

In [72]:
# Testing Data Evaluation
knn_clf = gscv_knn.best_estimator_
y_pred = knn_clf.predict(x_test)

cnf_matrix = confusion_matrix(y_test,y_pred)
print('\nConfusion Matrix is: \n', cnf_matrix)
print()
acc = accuracy_score(y_test,y_pred)
print('Accuracy is: ', acc)
print()
clf_report = classification_report(y_test,y_pred)
print('\nClassification Report is: \n',clf_report)

Confusion Matrix is:
 [[90 10]
 [34 20]]

Accuracy is:  0.7142857142857143


Classification Report is:
               precision    recall  f1-score   support

           0       0.73      0.90      0.80       100
           1       0.67      0.37      0.48        54

    accuracy                           0.71       154
   macro avg       0.70      0.64      0.64       154
weighted avg       0.71      0.71      0.69       154

In [73]:
# Training Data Evaluation

y_pred_train = knn_clf.predict(x_train)

cnf_matrix = confusion_matrix(y_train,y_pred_train)
print('\nConfusion Matrix is: \n', cnf_matrix)
print()
acc = accuracy_score(y_train,y_pred_train)
print('Accuracy is: ', acc)
print()
clf_report = classification_report(y_train,y_pred_train)
print('\nClassification Report is: \n',clf_report)

Confusion Matrix is:
 [[362  38]
 [105 109]]

Accuracy is:  0.7671009771986971


Classification Report is:
               precision    recall  f1-score   support

           0       0.78      0.91      0.84       400
           1       0.74      0.51      0.60       214

    accuracy                           0.77       614
   macro avg       0.76      0.71      0.72       614
weighted avg       0.76      0.77      0.75       614

Task:
    Whatever datasets we have crated after scaled the datasets, You have to build the model considering those datasets and compare the result too.